title: XeeNet
description: Distributed AI Research at Scale — An Open Platform for Autonomous ML Experimentation
baseurl: "/XeeNet"
url: "https://xeeva.github.io"
plugins: []
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
