title: XeeNet
description: Distributed AI Research at Scale
baseurl: "/XeeNet"
url: "https://xeeva.github.io"
plugins: []
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
